name: Deploy Next.js application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "MONGODB_URI=mongodb+srv://root:groot@echomatelite0.qsf5enp.mongodb.net/?retryWrites=true&w=majority" >> .env
          echo "MONGO_PASSWORD=broot" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
          echo "AWS_ACCESS_KEY_ID=AKIAY3LYQNH6OBGT373Q" >> .env
          echo "AWS_SECRET_ACCESS_KEY=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" >> .env
          echo "AWS_REGION=ap-south-1" >> .env
          echo "AWS_BUCKET_NAME=echomatelite" >> .env
          echo "NEXT_PUBLIC_BASE_URL=http://localhost:3000" >> .env
          cat .env
      - name: Build Docker image
        run: docker build -t echomatelite/nextjs-app .
      - name: login to docker hub
        run: echo "dckr_pat_7jb9Edk_DOPbrq5oJDaymOGAp1M" | docker login  -u keerthishree123 --password-stdin
      - name: Push Docker image
        run: docker push keerthishree123/nextjs_app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: delete old container
        run: docker rm -f nextjs-app-contianer
      - name: delete all old images
        run: docker rmi $(docker images -a -q)
      - name: pull image from docker hub
        run: docker pull echomatelite/nextjs-app:latest
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-contianer echomatelite/nextjs-app:latest
